sites/registrar+/apps/courses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
# import re

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'create$',views.create, name='create'),
    url(r'^(?P<id>\d+)/edit$',views.update, name='edit'),
    url(r'^(?P<id>\d+)/delete$',views.delete, name='delete'),
    url(r'^(?P<id>\d+)$',views.showCourse, name='show'),
]

sites/registrar+/apps/userloginreg/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$',views.register, name='create'),
    url(r'login$',views.login, name='login'),
    url(r'landingpage/$', views.landingpage, name='success'),
    url(r'logout$',views.logout, name='logout')
]

sites/registrar+/registrar/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^registrar/',include('apps.user_course.urls', namespace='registrar')),
    url(r'^$', include('apps.userloginreg.urls')),
    url(r'^home/', include('apps.userloginreg.urls', namespace='home')),
    url(r'^randomword/',include ('apps.timedisplay.urls')),
    url(r'^timed',include ('apps.timedisplay.urls')),
    url(r'^ninjas/', include('apps.ninjas.urls', namespace='ninjas')),
    url(r'^friendapp/',include('apps.friendapp.urls')),
    url(r'^admin/', admin.site.urls),
]

sites/registrar+/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models
from ..userloginreg.models import User
# Create your models here.

#This is not working for me....
class CourseExtendedManager(models.Manager):
    def ECsave(ECobj):
        courseObject = Course.objects.get(id = ECobj.course_id)
        courseObject.title = ECobj.course.title

        courseExtendedObject = CourseExtended.objects.get(course_id = ECobj.course_id)
        courseExtendedObject.description = ECobj.description
        try:
            courseObject.save()
            courseExtendedObject.save()
            return True
        except:
            return False

class Course(models.Model):
    title = models.CharField(max_length = 70, null = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user = models.ManyToManyField(User)

class CourseExtended(models.Model):
    course = models.OneToOneField( Course, on_delete = models.CASCADE, primary_key = True )
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects=CourseExtendedManager()

sites/registrar+/apps/courses/views.py
from django.shortcuts import render, redirect
from .models import Course, CourseExtended
# Create your views here.
def index(request):
    # User.objects.create(first_name="mike",last_name="mike",password="1234asdf")
    # models.Users.objects.filter(id__lte=7) | models.Users.objects.filter(id__gte=9)
    # courses = models.CourseExtended.objects.all()
    context = { 'courses': CourseExtended.objects.all().order_by('course__title') }

    # for each in context['courses']:
    #     print each.course.title, each.description, each.created_at, each.updated_at


    return render(request,'courses/index.html', context)

def create(request):
    if request.method == 'POST':
        temp = Course.objects.create(title = request.POST['title'])
        CourseExtended.objects.create(course_id=temp.id, description = request.POST['description'])
    return redirect('courses:index')

def showCourse(request,id):
    if request.method == 'GET':
        blah = CourseExtended.objects.get(course_id = id)
        context = {'course':blah }
        return render(request,'courses/show.html',context)
    return redirect('courses:index')

def update(request,id):

    if request.method == 'POST':
        blah = Course.objects.get(id = id)
        blah.title = request.POST['title']
        blah.save()

        data = CourseExtended.objects.get(course_id = id)
        data.course.title = request.POST['title']
        data.description = request.POST['description']
        data.save()
        return redirect('courses:index')
    return redirect('courses:index')

def delete(request,id):
    if request.method == 'GET':
        data = CourseExtended.objects.get(course_id = id)
        context = {'course':data}
        return render(request,'courses/delete.html',context)
    else:
        delete = Course.objects.get(id = id)
        delete.delete()
        return redirect('courses:index')
    return redirect('courses:index')

sites/registrar+/apps/courses/templates/courses/delete.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    {{course}}
    {{course.description}}
    <hr />
    <h1>Edit Course</h1>
    <form>
      {% csrf_token %}
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='title'>Title:</label>
        <p>{{course.course.title}}</p>
      </div>
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='description'>Description:</label>
        <span class='col-md-7'>{{course.description}}</span>
      </div>
      <div class='row'>
        <div class='col-md-offset-3 col-md-2'>
          <button class='btn btn-primary btn-block' formaction="/courses" formmethod='get' type='submit' name='cancel'>Cancel</button>
        </div>
        <div class='col-md-offset-1 col-md-2'>
          <button class='btn btn-danger btn-block' formaction="/courses/{{course.course_id}}/delete" formmethod='post' type='submit' name='delete'>Delete</button>
        </div>
      </div>
    </form>
  </div>
</body>
</html>

sites/registrar+/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Maintain Courses">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='col-md-10'>
        <h1>Courses</h1>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:success' %}">Dashboard</a>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:logout' %}">Logout</a>
      </div>
    </div>
    <form action='{% url 'courses:create' %}' method='POST'>
      {% csrf_token %}
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='title'>Title:</label>
        <input class='col-md-7' name='title'/>
      </div>
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='description'>Description:</label>
        <textarea class='col-md-7' name='description'></textarea>
      </div>
      <div class='row'>
        <div class='col-md-offset-3 col-md-3'>
          <button class='btn btn-primary btn-block' type='submit' name='create'>Create</button>
        </div>
      </div>
      </div>
    </form>
    <div id='window'>
      <table>
        <div class='row'>
          <thead>
            <tr>
              <td class='col-md-2'><strong>Course Title</strong></td>
              <td class='col-md-5'><strong>Description</strong></td>
              <td class='col-md-2'><strong>Created At</strong></td>
              <td class='col-md-2'><strong>Last Updated</strong></td>
              <td class='col-md-1'><strong>Action(s)</strong></td>
            </tr>
          </thead>
        </div>
        {% for row in courses %}
        <div class='row'>
          <tr>
            <td class='col-md-2'>{{row.course.title}}</td>
            <td class='col-md-5'>{{row.description}}</td>
            <td class='col-md-2'>{{row.created_at}}</td>
            <td class='col-md-2'>{{row.updated_at}}</td>
            <td class='col-md-1'><a href="{% url 'courses:show' id=row.course.id %}">Edit</a></td>
            <td class='col-md-1'><a href="{% url 'courses:delete' id=row.course.id %}">Delete</a></td>
          </tr>
        </div>
        {% endfor %}
            </table>
    </div>
  </div>
</body>
</html>

sites/registrar+/apps/courses/templates/courses/show.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    {{course}}
    {{course.description}}
    <hr />
    <h1>Edit Course</h1>
    <form method='POST'>
      {% csrf_token %}
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='title'>Title:</label>
        <input class='col-md-7' name='title' value="{{course.course.title}}"/>
      </div>
      <div class='formgroup row'>
        <label class='col-md-3 text-right' for='description'>Description:</label>
        <textarea class='col-md-7' name='description'>{{course.description}}</textarea>
      </div>
      <div class='row'>
        <div class='col-md-offset-3 col-md-2'>
          <button class='btn btn-success btn-block' formaction="{% url 'courses:edit' id=course.course.id %}" type='submit' name='update'>Update</button>
        </div>
        <div class='col-md-offset-1 col-md-2'>
          <button class='btn btn-danger btn-block' formaction="{% url 'courses:delete' id=course.course.id %}" type='submit' name='delete'>Delete</button>
        </div>
      </div>
    </form>
  </div>
</body>
</html>