sites/registrar+/apps/user_course/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'create$', views.create, name='create'),
]

sites/registrar+/apps/userloginreg/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$',views.register, name='create'),
    url(r'login$',views.login, name='login'),
    url(r'landingpage/$', views.landingpage, name='success'),
    url(r'logout$',views.logout, name='logout')
]

sites/registrar+/registrar/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^registrar/',include('apps.user_course.urls', namespace='registrar')),
    url(r'^$', include('apps.userloginreg.urls')),
    url(r'^home/', include('apps.userloginreg.urls', namespace='home')),
    url(r'^randomword/',include ('apps.timedisplay.urls')),
    url(r'^timed',include ('apps.timedisplay.urls')),
    url(r'^ninjas/', include('apps.ninjas.urls', namespace='ninjas')),
    url(r'^friendapp/',include('apps.friendapp.urls')),
    url(r'^admin/', admin.site.urls),
]

sites/registrar+/apps/user_course/models.py
from __future__ import unicode_literals

from django.db import models
from ..courses.models import Course, CourseExtended
from ..userloginreg.models import User
# Create your models here.

sites/registrar+/apps/user_course/views.py
from django.shortcuts import render, redirect
from . import models

# Create your views here.
def index(request):

    if not request.session['user_id']:
        return redirect('/home/')
    qcourses = models.CourseExtended.objects.all().order_by('course__title')
    course_data=[]
    for each in qcourses:
        ucount = 0
        for user in each.course.user.all():
            ucount += 1
        course_data.append({'students':ucount, 'description': each.description,
        'id': each.course.id, 'title':each.course.title
         })
    # qcourses = models.Course.objects.all().order_by('title')
    # course_data = []
    # for each in qcourses:
    #     eachX = models.CourseExtended.objects.get(course_id=each.id)
    #     ucount = 0
    #     for user in each.user.all():
    #         ucount += 1
    #     course_data.append({'students': ucount, 'description': eachX.description,
    #     'id':each.id, 'title':each.title,
    #      })
    #
    context={'users': models.User.objects.all(),
             'courses': qcourses,
             'user' : models.User.objects.get(id = request.session['user_id']),
             'course_stats' : course_data
    }
    return render(request, 'user_course/index.html',context=context)
def create(request):

    if not request.session['user_id']:
        return redirect('/home/')
    if not request.method=='POST':
        return redirect('registrar:index')
    ufid = int(request.POST['user'])
    cfid = int(request.POST['course'])
    uf = models.User.objects.get(id= ufid)
    cf = models.Course.objects.get(id= cfid)
    cf.user.add(uf)
    cf.save()
    return redirect('registrar:index')

sites/registrar+/apps/user_course/templates/user_course/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Assign Users to Courses">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='col-md-10'>
        <h1>Assign Users to Courses</h1>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:success' %}">Dashboard</a>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:logout' %}">Logout</a>
      </div>
    </div>
    <div class='row'>
      <form>
        {% csrf_token %}
        <label class='col-md-1 text-right'>Users:</label>
          <select class = 'col-md-3' name="user">
            {% for each in users %}
            <option value={{each.id}}>{{each.first_name}} {{each.last_name}}</option>
            {% endfor %}
          </select>
        <label for='courses' class='col-md-1 text-right'>Course:</label>
          <select  class='col-md-2' name="course">
            {% for each in courses %}
            <option value={{each.course.id}}>{{each.course.title}}</option>
            {% endfor %}
          </select>
        <div class='col-md-1'>
          <input class='btn btn-primary' type='submit' formaction='{% url 'registrar:create' %}' formmethod='POST'/>
        </div>
      </form>
    </div>
    <div id='courses'>
      <table>
        <thead>
          <tr><th>Class</th><th>Description</th><th>Students</th><th>Actions</th></tr>
        </thead>
        <tbody>
          {% for class in course_stats %}
          <div class='row'>
            <tr><td class='col-md-3'>{{class.title}}</td>
              <td class='col-md-6'>{{class.description}}</td>
              <td class='col-md-2'>{{class.students}}</td>
              <td class='col-md-2'><a href='#Show'>Show</a></td></tr>
          </div>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>