sites/registrar+/apps/ninjas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^([a-zA-Z]+)$', views.index),
    url(r'^', views.index, name='ninjas'),
]

sites/registrar+/apps/userloginreg/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$',views.register, name='create'),
    url(r'login$',views.login, name='login'),
    url(r'landingpage/$', views.landingpage, name='success'),
    url(r'logout$',views.logout, name='logout')
]

sites/registrar+/registrar/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^registrar/',include('apps.user_course.urls', namespace='registrar')),
    url(r'^$', include('apps.userloginreg.urls')),
    url(r'^home/', include('apps.userloginreg.urls', namespace='home')),
    url(r'^randomword/',include ('apps.timedisplay.urls')),
    url(r'^timed',include ('apps.timedisplay.urls')),
    url(r'^ninjas/', include('apps.ninjas.urls', namespace='ninjas')),
    url(r'^friendapp/',include('apps.friendapp.urls')),
    url(r'^admin/', admin.site.urls),
]

sites/registrar+/apps/userloginreg/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt, re
# Create your models here.

class UserManager(models.Manager):

    def register(self,data):

        email = data['email'].strip().lower()
        first_name = data['first_name'].strip()
        last_name = data['last_name'].strip()
        password = data['password'].strip()

        error = False
        errors = []
        if len(first_name) < 1:
            errors.append('Please enter a first name')
        if len(last_name) < 1:
            errors.append('Please enter a last name')
        if len(password) < 8:
            errors.append('Password must be at least 8 in length')
        if not re.search(r'[0-9]',password):
            errors.append('Password should contain at least one number.')
        if not re.search(r'[A-Z]',password):
            errors.append('Password should contain at least one uppercase.')
        if not re.search(r'[a-z]',password):
            errors.append('Password should contain at least one lowercase.')
        if not re.search(r'[~!@#$%^&*_+]',password):
            errors.append('Password should have at least one of these: ~!@#$%^&*_+')
        if not re.search(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$',email):
            errors.append('Enter a valid email address.')
        if data['password'] != data['password2']:
            errors.append('Password and validation password do not match.')

        if len(User.objects.filter(email=email)) > 0:
            errors.append('This email is already registered.')

        if len(errors) > 0:
            error = True
        # print email, first_name, last_name
        if error == False:
            # encrypt password
            # put stuff in  front of .Create
            temp = password.encode()
            hashed = bcrypt.hashpw(temp,bcrypt.gensalt())
            user = User.objects.create(email=email, first_name=first_name, last_name=last_name, password=hashed)
            # clear the password but pass the whole user object back so a landign page can user
            # user first name last name and email without .get, if desired
            user.password = '*cleared'
            user_dict={'user_id':user.id, 'first_name':user.first_name,'last_name':user.last_name,'email':user.email}
            return (True, user_dict)
        else:
            return (False, errors)

    def login(self, data):

        print data
        email = data['user'].strip().lower()
        attempt = data['password'].strip()

        row = User.objects.filter(email=email)

        if len(row) == 1:
            attempt = attempt.encode()
            login = bcrypt.checkpw(attempt, row[0].password.encode())

            if login == True:
                print "Login Successful:", email
                row[0].password='*cleared'
                rdata = row[0]
            else:
                print "Login Failed:", email
                rdata = ['user/password combination not correct.']
        else:
            login = False
            rdata = ['User ID is invalid for login.']

        return (login, rdata)


class User(models.Model):
    email = models.EmailField(max_length = 100, null = False)
    password = models.CharField(max_length = 255 )
    first_name = models.CharField(max_length = 45)
    last_name = models.CharField(max_length = 45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

sites/registrar+/apps/userloginreg/views.py
from django.shortcuts import render, redirect
from . import models
from django.core.urlresolvers import reverse
# Create your views here.
# home route
def index(request):

    errors=[]
    context = {}

    if 'errors' in request.session:
        errors = request.session['errors']
        context['error'] = True
        context['errors'] = errors
        context['formdata'] = request.session['formdata']
        del request.session['errors']
        del request.session['formdata']

    elif 'new' in request.session:
        context['formdata'] = request.session['formdata']
        context['new'] = True
        del request.session['new']
        del request.session['formdata']

    return render(request,'userloginreg/index.html',context)

def login(request):
    if request.method == 'POST':
        ( flag, data ) = models.User.objects.login(request.POST)
        if flag == True:
            request.session['user_id'] = data.id
            request.session['login'] = True
            return redirect('home:success')
        else:
            request.session['login'] = False
            request.session['formdata'] = {'email': request.POST['user']}
            request.session['errors'] = data
            return redirect('home:index')
    else:
        return redirect('home:index')
def logout(request):
        request.session.clear()
        return redirect('home:index')
def register(request):

    print "register():"
    if request.method == 'POST':

        if 'login' in request.session:
            del request.session['login']

        ( flag , data ) = models.User.objects.register(request.POST)

        if flag == True:
            # fill formdata with the scrubbed successful data
            formdata = {'first_name': data['first_name'],'last_name': data['last_name'],'email': data['email']}
            request.session['formdata'] = formdata
            request.session['new'] = True
        else:
            request.session['errors'] = data
            # fill formdata with the same stuff the user entered into the form
            formdata = {'first_name': request.POST['first_name'],'last_name': request.POST['last_name'],'email': request.POST['email']}
            request.session['formdata'] = formdata

        return redirect('home:index')
    else:
        return redirect('home:index')

def landingpage(request):

    if request.session['user_id']:
        context = {}
        z = models.User.objects.get(id=request.session['user_id'])
        context['user'] = { 'first_name': z.first_name, 'last_name': z.last_name, 'email': z.email }
        return render(request,'userloginreg/landingpage.html', context)
    else:
        return redirect('home:index')

sites/registrar+/apps/userloginreg/templates/userloginreg/index.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
  <h1>Login / Register</h1>
  <div id='login'>
    <p>{% if new %}Registration is complete. Please Login in!{% endif %}</p>
    <form method='POST' action='/home/login'>
      {% csrf_token %}
      <input type='text' placeholder='e-mail' name='user'
        {% if new %}
        value="{{formdata.email}}"
        {% endif %}
        />
      <input type='password' placeholder='Password' name='password' />
      <button type='submit'>Login</button>
    </form>
  </div>
  <div id='register'>
    <form method='POST' action='/home/register'>
      {% csrf_token %}
      <input type='text' placeholder='First Name' name='first_name'
        {% if error %}
        value="{{formdata.first_name}}"
        {% endif %}
        />
      <input type='text' placeholder='Last Name' name='last_name'
        {% if error %}
        value="{{formdata.last_name}}"
        {% endif %}
        />
      <input type='text' placeholder='e-mail' name='email'
        {% if error %}
        value="{{formdata.email}}"
        {% endif %}
        />
      <input type='password' placeholder='Password' name='password' />
      <input type='password' placeholder='Confirm Password' name='password2' />
      <button type='submit'>Create</button>
    </form>
  </div>
  <div id='errors' {% if error == True %}style='display: inline-block;'{% else %}style='display: none;'{% endif %}>
    {% if error == True %}
    {% for each in errors %}
    <p class='error'>{{each}}</p>
    {% endfor %}
    {% endif %}
  </div>
</body>
</html>

sites/registrar+/apps/userloginreg/templates/userloginreg/landingpage.html
<! DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Assign Users to Courses">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet" />
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='col-md-10'>
        <h1>Dashboard</h1>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:success' %}">Dashboard</a>
      </div>
      <div class='col-md-1'>
        <a class='btn btn-primary' href="{% url 'home:logout' %}">Logout</a>
      </div>
    </div>
  <p>
    Welcome, {{ user.first_name}} {{user.last_name}}
  </p>
  <hr />
  <ul>
    <li><a href="{% url 'courses:index' %}" >Maintain Courses</a></li>
    <li><a href="{% url 'registrar:index' %}" >Register Users in Courses</a></li>
    <li><a href="{% url 'ninjas:ninjas' %}" >Play with Turtles</a></li>
  </ul>
    </div>
</body>
</html>

sites/registrar+/apps/userloginreg/templates/userloginreg/success.html
<! DOCTYPE html>
<html>
<head>

</head>
<body>
  <h1>Hello World</h1>
  <p>
    {{ new_user.first_name}}, {{new_user.last_name}}
  </p>
  <hr />
  {% for each in users %}
    <p>
      {{each.first_name}} {{each.last_name}}, {{each.email}}
    </p>
  {%  endfor%}
</body>
</html>